<?php

$configPath = __DIR__ . DIRECTORY_SEPARATOR . 'config.php';

if (file_exists($configPath)) {
  header('Location: index.php');
  exit;
}

require_once __DIR__ . DIRECTORY_SEPARATOR . 'php' . DIRECTORY_SEPARATOR . 'migrate.php';

$error = '';
$values = [
  'dbhost' => 'localhost',
  'dbuser' => 'root',
  'dbpass' => '',
  'db' => 'time_sheets',
  'timezone' => 'Australia/Brisbane',
];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  $values['dbhost'] = trim((string) ($_POST['dbhost'] ?? ''));
  $values['dbuser'] = trim((string) ($_POST['dbuser'] ?? ''));
  $values['dbpass'] = (string) ($_POST['dbpass'] ?? '');
  $values['db'] = trim((string) ($_POST['db'] ?? ''));
  $values['timezone'] = trim((string) ($_POST['timezone'] ?? 'UTC'));

  try {
    if ($values['dbhost'] === '' || $values['dbuser'] === '' || $values['db'] === '') {
      throw new RuntimeException('Host, username, and database name are required.');
    }

    if (!preg_match('/^[A-Za-z0-9_]+$/', $values['db'])) {
      throw new RuntimeException('Database name may only contain letters, numbers, and underscores.');
    }

    if (!in_array($values['timezone'], timezone_identifiers_list(), true)) {
      throw new RuntimeException('Invalid timezone.');
    }

    mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);
    $conn = new mysqli($values['dbhost'], $values['dbuser'], $values['dbpass']);
    $conn->set_charset('utf8mb4');

    tt_write_config($configPath, $values);
    tt_ensure_database_and_migrate($conn, $values['db']);
    $conn->close();

    header('Location: index.php');
    exit;
  } catch (Throwable $e) {
    if (file_exists($configPath)) {
      @unlink($configPath);
    }
    $error = $e->getMessage();
  }
}

/**
 * @param string $path
 * @param array{dbhost:string,dbuser:string,dbpass:string,db:string,timezone:string} $values
 */
function tt_write_config($path, array $values)
{
  $export = static function ($value) {
    return var_export((string) $value, true);
  };

  $contents = "<?php\n\n"
    . "// Database Connect\n"
    . "// Generated by install.php — do not commit this file.\n\n"
    . '$dbhost = ' . $export($values['dbhost']) . ";\n"
    . '$dbuser = ' . $export($values['dbuser']) . ";\n"
    . '$dbpass = ' . $export($values['dbpass']) . ";\n"
    . '$db = ' . $export($values['db']) . ";\n\n"
    . 'date_default_timezone_set(' . $export($values['timezone']) . ");\n";

  if (file_put_contents($path, $contents) === false) {
    throw new RuntimeException(
      'Could not write config.php. Check that the application directory is writable.'
    );
  }
}

function h($value)
{
  return htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Install Time Tracking</title>
  <link rel="stylesheet" href="styles/styles.css">
  <style>
    .install-wrap {
      max-width: 32rem;
      margin: 2rem auto;
      padding: 0 1rem;
    }
    .install-wrap label {
      display: block;
      margin-top: 0.75rem;
      font-weight: 600;
    }
    .install-wrap input {
      width: 100%;
      box-sizing: border-box;
      margin-top: 0.25rem;
      padding: 0.4rem 0.5rem;
    }
    .install-wrap .hint {
      color: #666;
      font-size: 0.9rem;
      margin-top: 0.25rem;
    }
    .install-error {
      background: #fde8e8;
      border: 1px solid #c0392b;
      color: #922b21;
      padding: 0.75rem 1rem;
      margin: 1rem 0;
    }
    .install-wrap button {
      margin-top: 1.25rem;
      padding: 0.5rem 1rem;
      cursor: pointer;
    }
  </style>
</head>
<body>
  <div class="install-wrap">
    <h1>Install Time Tracking</h1>
    <p>Enter your MySQL connection details. The database will be created if it does not exist, and the schema will be installed.</p>

    <?php if ($error !== '') : ?>
      <div class="install-error"><?php echo h($error); ?></div>
    <?php endif; ?>

    <form method="post" action="install.php">
      <label for="dbhost">MySQL host</label>
      <input id="dbhost" name="dbhost" required value="<?php echo h($values['dbhost']); ?>">

      <label for="dbuser">Username</label>
      <input id="dbuser" name="dbuser" required value="<?php echo h($values['dbuser']); ?>">

      <label for="dbpass">Password</label>
      <input id="dbpass" name="dbpass" type="password" value="<?php echo h($values['dbpass']); ?>">

      <label for="db">Database name</label>
      <input id="db" name="db" required pattern="[A-Za-z0-9_]+" value="<?php echo h($values['db']); ?>">
      <p class="hint">Letters, numbers, and underscores only.</p>

      <label for="timezone">Timezone</label>
      <input id="timezone" name="timezone" required value="<?php echo h($values['timezone']); ?>">
      <p class="hint">PHP timezone identifier, e.g. Australia/Brisbane</p>

      <button type="submit">Install</button>
    </form>
  </div>
</body>
</html>
